GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/65b68496882c1b02c01d15c4

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Akos Dabasi",
    "number": "023012314014"
}

###
DELETE http://localhost:3001/api/persons/65b68496882c1b02c01d15c7dd